### ISSUE TITLE
[doc] request for map documentation

### ISSUE THREAD

**Issue by hpsaturn** [jgauchia/IceNav-v3#1]
## Overview

Great project. I want contribute with the project. My first goal will be try to run a minimal version on T-Display board with my GPS and maybe with the minimal resources files into the user partition flash. For that, is possible describe the procedure to have the map or a basic guide of the map files generation?

**Comment by jgauchia** [comment]
Ok, no problem. I'll made documentation as soon as possible , maybe I'll publish a wiki , etc.

**Comment by jgauchia** [comment]
Map folder structure updated in README.md .

**Comment by jgauchia** [comment]
Maps are generated by Maperitive app, tiles output structure matches with IceNav map tiles structure
