### ISSUE TITLE
Support for  ELECROW ESP32 Terminal

### ISSUE THREAD

**Issue by Shreyashsatone** [jgauchia/IceNav-v3#192]
I am using board "ELECROW ESP32 Terminal". hear is the board link :-
https://robu.in/product/elecrow-esp32-terminal-with-esp32-3-5-inch-parallel-480x320-tft-capacitive-touch-rgb-displayrgb-by-chip-ili9488/?gad_source=1&gclid=Cj0KCQjwzva1BhD3ARIsADQuPnUBL5Wnh72beYLEnL0SMpd0_4TPQ-3lfNj_WxJGONgNmg5aiVz-tloaAmN6EALw_wcB

I was able to successfully deploy. But the Display of the board did not turne on and the code did not work no the ELECROW ESP32 Terminal.

Pin config:-
cfg.pin_wr = 18;  // pin number connecting WR
            cfg.pin_rd = 48;  // pin number connecting RD
            cfg.pin_rs = 45;  // Pin number connecting RS(D/C)
            cfg.pin_d0 = 47;  // pin number connecting D0
            cfg.pin_d1 = 21;  // pin number connecting D1
            cfg.pin_d2 = 14;  // pin number connecting D2
            cfg.pin_d3 = 13;  // pin number connecting D3
            cfg.pin_d4 = 12;  // pin number connecting D4
            cfg.pin_d5 = 11;  // pin number connecting D5
            cfg.pin_d6 = 10;  // pin number connecting D6
            cfg.pin_d7 = 9;   // pin number connecting D7
            cfg.pin_d8 = 3;   // pin number connecting D8
            cfg.pin_d9 = 8;   // pin number connecting D9
            cfg.pin_d10 = 16; // pin number connecting D10
            cfg.pin_d11 = 15; // pin number connecting D11
            cfg.pin_d12 = 7;  // pin number connecting D12
            cfg.pin_d13 = 6;  // pin number connecting D13
            cfg.pin_d14 = 5;  // pin number connecting D14
            cfg.pin_d15 = 4;  // pin number connecting D15

**Comment by jgauchia** [comment]
- [ ] Review Board definitions
- [ ] Add support to ELECROW ESP32 Terminal

**Comment by jgauchia** [comment]
Branch https://github.com/jgauchia/IceNav-v3/tree/devel_support_elecrow_esp32 updated

https://youtube.com/shorts/3VFcUI6n7OQ
