### ISSUE TITLE
NMEA decoding baudrate is wrong

### ISSUE THREAD

**Issue by hpsaturn** [jgauchia/IceNav-v3#221]
## Overview

Sometimes, after performing manual reboots via the CLI, attempting to request the outnmea command results in bad characters, indicating that the baud rate may be incorrect. Additionally, you may notice that the main clock in the status bar displays an incorrect time of 00:00:00. If you perform one more reboot, the problem disappears. I believe this issue has been present in past versions, possibly in the master version, as the clock issue and the inability to synchronize GPS sometimes.

**Comment by jgauchia** [comment]
Maybe it's a problem when autobaud is selected.
I'll check it.

**Comment by jgauchia** [comment]
Unified in issue #236
