### ISSUE TITLE
Zoom issues

### ISSUE THREAD

**Issue by jgauchia** [jgauchia/IceNav-v3#43]
## Overview
Some zoom levels do not display the map.

**Comment by jgauchia** [comment]
For now, I'm unable to reproduce the error. I'll keep the issue open.

**Comment by jgauchia** [comment]
@hpsaturn please try the branch associated to the issue before merging into the master branch.

**Comment by hpsaturn** [comment]
Nop, I merged `43-zoom-issues` into my `mpu9250` branch (current mpu9250 PR), and nothing.

**Comment by jgauchia** [comment]
Ok,I'll review it again to see.

**Comment by jgauchia** [comment]
Branch updated, 
Please test it.

**Comment by jgauchia** [comment]
Fixed in master branch
