### ISSUE TITLE
Program freezes when GPS signal is present with environment vars

### ISSUE THREAD

**Issue by jgauchia** [jgauchia/IceNav-v3#78]
## Overview
If upload the code with environment vars for debugging , when GPS signal is fixed the program freezes.
No console output.

**Comment by jgauchia** [comment]
Maybe the problem is with Notify Bar,

**Comment by jgauchia** [comment]
The problem is in GPS encode data, when disabled not freeze

**Comment by jgauchia** [comment]
@hpsaturn I've changed GPS encode function to a Task again, please, can you test in your board the last commit in master branch?
Thank you

**Comment by hpsaturn** [comment]
working in the debug version (with environment variables) and the production version :+1:

**Comment by jgauchia** [comment]
Thanks  @hpsaturn , 
Issue closed

**Comment by jgauchia** [comment]
Seems not work well

**Comment by jgauchia** [comment]
Bug caused by LV_LED widget

**Comment by jgauchia** [comment]
Delete led widget from notify bar
