### ISSUE TITLE
Firmware Upgrade

### ISSUE THREAD

**Issue by jgauchia** [jgauchia/IceNav-v3#85]
Add firmware upgrade from SD file

**Comment by hpsaturn** [comment]
I think that we could have this in the WCLI library, in this layer, similar to telnet service, o maybe enable/disable via flag. The other thing is FOTA updates, that is a different challenge, but maybe will nice to have in this layer too.

**Comment by jgauchia** [comment]
> I think that we could have this in the WCLI library, in this layer, similar to telnet service, o maybe enable/disable via flag. The other thing is FOTA updates, that is a different challenge, but maybe will nice to have in this layer too.

Ok! no problem
